import {
  Ambulance,
  BriefcaseBusiness,
  Building2,
  CarFront,
  GraduationCap,
  HeartPulse,
  Home,
  PaintRoller,
  Package,
  Paintbrush2,
  PartyPopper,
  Plug,
  ShieldCheck,
  ShieldAlert,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Truck,
  Trees,
  Hammer,
  Wrench,
} from 'lucide-react'

export const lokalsTheme = {
  colors: {
    primary: '#3F2BCB',
    purple: '#3F2BCB',
    purpleDeep: '#2B1E8C',
    charcoal: '#0F172A',
    gold: '#FACC15',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    success: '#16A34A',
    warning: '#F59E0B',
    danger: '#EF4444',
    info: '#2563EB',
    muted: '#6B7280',
    border: '#E5E7EB',
  },
  radius: {
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    hero: '24px',
  },
}

export const quickActions = [
  { label: 'Taxi', to: '/ride', color: 'bg-sky-50 text-sky-700', icon: CarFront },
  { label: 'Delivery', to: '/delivery', color: 'bg-emerald-50 text-emerald-700', icon: Package },
  { label: 'SOS', to: '/sos', color: 'bg-rose-50 text-rose-700', icon: ShieldAlert },
  { label: 'Marketplace', to: '/marketplace', color: 'bg-lokals-gold-soft text-lokals-charcoal', icon: ShoppingBag },
  { label: 'Events', to: '/events', color: 'bg-violet-50 text-lokals-purple', icon: Building2 },
  { label: 'News', to: '/news', color: 'bg-fuchsia-50 text-lokals-purple-deep', icon: Sparkles },
]

export const categoryMeta = {
  services: { icon: Sparkles, color: 'bg-violet-50 text-lokals-purple' },
  jobs: { icon: BriefcaseBusiness, color: 'bg-lokals-sky-soft text-lokals-info' },
  marketplace: { icon: ShoppingBag, color: 'bg-lokals-gold-soft text-lokals-charcoal' },
  delivery: { icon: Package, color: 'bg-emerald-50 text-emerald-700' },
  ride: { icon: CarFront, color: 'bg-violet-50 text-violet-700' },
  sos: { icon: ShieldAlert, color: 'bg-rose-50 text-rose-700' },
  health: { icon: HeartPulse, color: 'bg-emerald-50 text-emerald-700' },
  beauty: { icon: Paintbrush2, color: 'bg-pink-50 text-pink-700' },
  plumbing: { icon: Wrench, color: 'bg-sky-50 text-sky-700' },
  electrical: { icon: Plug, color: 'bg-yellow-50 text-yellow-700' },
  cleaning: { icon: Sparkles, color: 'bg-cyan-50 text-cyan-700' },
  mechanics: { icon: Wrench, color: 'bg-orange-50 text-orange-700' },
  tutors: { icon: Building2, color: 'bg-indigo-50 text-indigo-700' },
  carpentry: { icon: Hammer, color: 'bg-amber-50 text-amber-700' },
  painting: { icon: PaintRoller, color: 'bg-rose-50 text-rose-700' },
  garden: { icon: Trees, color: 'bg-emerald-50 text-emerald-700' },
  repair: { icon: ShieldCheck, color: 'bg-slate-100 text-slate-700' },
  moving: { icon: Truck, color: 'bg-blue-50 text-blue-700' },
  entertainment: { icon: PartyPopper, color: 'bg-fuchsia-50 text-fuchsia-700' },
  education: { icon: GraduationCap, color: 'bg-indigo-50 text-indigo-700' },
  automotive: { icon: CarFront, color: 'bg-orange-50 text-orange-700' },
  public_services: { icon: Building2, color: 'bg-violet-50 text-violet-700' },
  home_maintenance: { icon: Home, color: 'bg-teal-50 text-teal-700' },
  directory: { icon: Home, color: 'bg-fuchsia-50 text-lokals-purple-deep' },
  announcements: { icon: Stethoscope, color: 'bg-lokals-sky-soft text-lokals-info' },
  default: { icon: Ambulance, color: 'bg-slate-100 text-slate-700' },
} as const
