<?php

use App\Http\Controllers\Api\AdminController;
use App\Http\Controllers\Api\AdminHireController;
use App\Http\Controllers\Api\AdminOrderController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AlertFeedController;
use App\Http\Controllers\Api\BookingController;
use App\Http\Controllers\Api\BlockController;
use App\Http\Controllers\Api\BusinessController;
use App\Http\Controllers\Api\CityServiceController;
use App\Http\Controllers\Api\CommunityProjectController;
use App\Http\Controllers\Api\CommunityImpactController;
use App\Http\Controllers\Api\ConversationController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DeliveryController;
use App\Http\Controllers\Api\DeviceTokenController;
use App\Http\Controllers\Api\FeedController;
use App\Http\Controllers\Api\EventController;
use App\Http\Controllers\Api\FollowController;
use App\Http\Controllers\Api\FollowFeedController;
use App\Http\Controllers\Api\HireBookingController;
use App\Http\Controllers\Api\HireItemController;
use App\Http\Controllers\Api\JobController;
use App\Http\Controllers\Api\AccommodationController;
use App\Http\Controllers\Api\AdminFeedController;
use App\Http\Controllers\Api\AiAssistController;
use App\Http\Controllers\Api\ListingController;
use App\Http\Controllers\Api\MeController;
use App\Http\Controllers\Api\ModerationController;
use App\Http\Controllers\Api\NewsController;
use App\Http\Controllers\Api\NewsSourceController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OrganizationController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PreferenceController;
use App\Http\Controllers\Api\PostDraftController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\QueueHealthController;
use App\Http\Controllers\Api\RoleApplicationController;
use App\Http\Controllers\Api\RideController;
use App\Http\Controllers\Api\SafetyController;
use App\Http\Controllers\Api\SearchController;
use App\Http\Controllers\Api\SavedItemController;
use App\Http\Controllers\Api\RealtimeHealthController;
use App\Http\Controllers\Api\SellerOrderController;
use App\Http\Controllers\Api\ServiceProviderController;
use App\Http\Controllers\Api\SosController;
use App\Http\Controllers\Api\SupportController;
use App\Http\Controllers\Api\SubscriptionController;
use App\Http\Controllers\Api\ActivityController;
use App\Http\Controllers\Api\AdminRoleApplicationController;
use App\Http\Controllers\Api\AdminCommunityProjectController;
use App\Http\Controllers\Api\AdminCommunityImpactController;
use App\Http\Controllers\Api\WorkerController;
use App\Http\Controllers\Api\CourierOrderController;
use Illuminate\Support\Facades\Route;

Route::get('/health', function () {
    return response()->json([
        'status' => 'ok',
        'app' => 'LOKALS',
        'environment' => app()->environment(),
    ]);
});

Route::prefix('v1')->group(function (): void {
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/login', [AuthController::class, 'login']);

    Route::get('/feed', [FeedController::class, 'index']);
    Route::get('/feed/{feedPost}', [FeedController::class, 'show']);
    Route::get('/feed-categories', [FeedController::class, 'categories']);
    Route::get('/marketplace', [ListingController::class, 'index']);
    Route::get('/marketplace/{listing}', [ListingController::class, 'show']);
    Route::get('/jobs', [JobController::class, 'index']);
    Route::get('/jobs/{job}', [JobController::class, 'show']);
    Route::get('/workers', [WorkerController::class, 'index']);
    Route::get('/workers/{worker}', [WorkerController::class, 'show']);
    Route::get('/directory', [OrganizationController::class, 'index']);
    Route::get('/directory/{organization}', [OrganizationController::class, 'show']);
    Route::get('/directory/{organization}/alerts', [OrganizationController::class, 'alerts']);
    Route::get('/organizations/{organization}', [OrganizationController::class, 'show']);
    Route::get('/store/products', [ProductController::class, 'index']);
    Route::get('/store/products/{product}', [ProductController::class, 'show']);
    Route::get('/store/sale-alerts', [ProductController::class, 'saleAlerts']);
    Route::get('/hire/items', [HireItemController::class, 'index']);
    Route::get('/hire/items/{hireItem}', [HireItemController::class, 'show']);
    Route::get('/accommodations', [AccommodationController::class, 'index']);
    Route::get('/accommodations/{accommodation}', [AccommodationController::class, 'show']);
    Route::get('/announcements', [CityServiceController::class, 'announcements']);
    Route::get('/alerts', [CityServiceController::class, 'alerts']);
    Route::get('/alerts/feed', [AlertFeedController::class, 'index']);
    Route::get('/news', [NewsController::class, 'index']);
    Route::get('/news/feed', [NewsController::class, 'feed']);
    Route::get('/news/trending', [NewsController::class, 'trending']);
    Route::get('/news/local', [NewsController::class, 'local']);
    Route::get('/news/{newsItem}', [NewsController::class, 'show']);
    Route::get('/events', [EventController::class, 'index']);
    Route::get('/events/calendar', [EventController::class, 'calendar']);
    Route::get('/events/upcoming', [EventController::class, 'upcoming']);
    Route::get('/events/nearby', [EventController::class, 'nearby']);
    Route::get('/events/{event}', [EventController::class, 'show']);
    Route::get('/events/{event}/calendar.ics', [EventController::class, 'downloadCalendar']);
    Route::get('/community-projects', [CommunityProjectController::class, 'index']);
    Route::get('/community-projects/featured', [CommunityProjectController::class, 'featured']);
    Route::get('/community-projects/{slug}', [CommunityProjectController::class, 'show']);
    Route::get('/community-project-categories', [CommunityProjectController::class, 'categories']);
    Route::get('/search', [SearchController::class, 'index']);
    Route::get('/service-providers', [ServiceProviderController::class, 'index']);
    Route::get('/service-providers/{serviceProvider}', [ServiceProviderController::class, 'show']);
    Route::get('/service-providers/{serviceProvider}/services', [ServiceProviderController::class, 'services']);
    Route::get('/service-providers/{serviceProvider}/availability', [ServiceProviderController::class, 'availability']);
    Route::get('/subscription-plans', [SubscriptionController::class, 'index']);

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::post('/auth/switch-role', [AuthController::class, 'switchRole']);
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::get('/dashboard/citizen', [DashboardController::class, 'citizen']);
        Route::get('/dashboard/worker', [DashboardController::class, 'worker']);
        Route::get('/dashboard/seller', [DashboardController::class, 'business']);
        Route::get('/dashboard/business', [DashboardController::class, 'business']);
        Route::get('/dashboard/service-provider', [DashboardController::class, 'serviceProvider']);
        Route::get('/dashboard/organization', [DashboardController::class, 'organization']);
        Route::get('/dashboard/municipality', [DashboardController::class, 'municipality']);
        Route::get('/dashboard/town-manager', [DashboardController::class, 'municipality']);
        Route::get('/dashboard/driver', [DashboardController::class, 'driver']);
        Route::get('/dashboard/courier', [DashboardController::class, 'courier']);
        Route::get('/dashboard/admin', [DashboardController::class, 'admin']);
        Route::get('/realtime/health', RealtimeHealthController::class);
        Route::get('/queue/health', QueueHealthController::class);
        Route::get('/my/roles', [RoleApplicationController::class, 'myRoles']);
        Route::get('/my/modes', [RoleApplicationController::class, 'myModes']);
        Route::patch('/my/current-mode', [RoleApplicationController::class, 'updateCurrentMode']);
        Route::post('/role-applications', [RoleApplicationController::class, 'store']);
        Route::get('/my/role-applications', [RoleApplicationController::class, 'index']);
        Route::get('/my/role-applications/{id}', [RoleApplicationController::class, 'show']);
        Route::patch('/my/role-applications/{id}', [RoleApplicationController::class, 'update']);
        Route::post('/my/role-applications/{id}/submit', [RoleApplicationController::class, 'submit']);

        Route::get('/me', [MeController::class, 'show']);
        Route::put('/me', [MeController::class, 'update']);
        Route::post('/profile/avatar', [MeController::class, 'uploadAvatar']);
        Route::get('/preferences', [PreferenceController::class, 'show']);
        Route::put('/preferences', [PreferenceController::class, 'update']);

        Route::post('/follow', [FollowController::class, 'store']);
        Route::get('/follow', [FollowController::class, 'index']);
        Route::delete('/follow/{follow}', [FollowController::class, 'destroy']);
        Route::post('/directory/{organization}/follow', [OrganizationController::class, 'follow']);
        Route::post('/community-projects', [CommunityProjectController::class, 'store']);
        Route::get('/my/community-projects', [CommunityProjectController::class, 'myProjects']);
        Route::get('/my/community-projects/{id}', [CommunityProjectController::class, 'myProjectShow']);
        Route::patch('/my/community-projects/{id}', [CommunityProjectController::class, 'update']);
        Route::post('/community-projects/{id}/pledges', [CommunityProjectController::class, 'pledge']);
        Route::get('/my/community-project-pledges', [CommunityProjectController::class, 'myPledges']);
        Route::post('/community-projects/{id}/updates', [CommunityProjectController::class, 'storeUpdate']);
        Route::post('/community-projects/{id}/follow', [CommunityProjectController::class, 'follow']);
        Route::delete('/community-projects/{id}/follow', [CommunityProjectController::class, 'unfollow']);
        Route::get('/following-feed', [FollowFeedController::class, 'index']);
        Route::get('/activity', [ActivityController::class, 'index']);
        Route::post('/feed/{feedPost}/save', [FeedController::class, 'save']);
        Route::post('/feed/{feedPost}/hide', [FeedController::class, 'hide']);
        Route::post('/feed/{feedPost}/report', [FeedController::class, 'report']);
        Route::get('/my/feed-preferences', [FeedController::class, 'preferences']);
        Route::patch('/my/feed-preferences', [FeedController::class, 'updatePreferences']);
        Route::post('/ai/assist/marketplace', [AiAssistController::class, 'marketplace']);
        Route::post('/ai/assist/issue-report', [AiAssistController::class, 'issueReport']);
        Route::post('/ai/assist/community-project', [AiAssistController::class, 'communityProject']);
        Route::post('/ai/assist/business', [AiAssistController::class, 'business']);
        Route::get('/ai/assist/{aiAssistRequest}', [AiAssistController::class, 'show']);
        Route::post('/support/chat', [SupportController::class, 'chat']);
        Route::get('/support/conversations', [SupportController::class, 'conversations']);
        Route::get('/support/conversations/{conversation}', [SupportController::class, 'show']);
        Route::post('/support/conversations/{conversation}/messages', [SupportController::class, 'message']);
        Route::post('/support/conversations/{conversation}/escalate', [SupportController::class, 'escalate']);
        Route::get('/community-impact/me', [CommunityImpactController::class, 'me']);
        Route::get('/community-impact/my-transactions', [CommunityImpactController::class, 'myTransactions']);
        Route::get('/community-impact/rewards', [CommunityImpactController::class, 'rewards']);
        Route::post('/community-impact/rewards/{id}/redeem', [CommunityImpactController::class, 'redeem']);
        Route::get('/community-impact/my-redemptions', [CommunityImpactController::class, 'myRedemptions']);
        Route::patch('/community-impact/privacy-settings', [CommunityImpactController::class, 'updatePrivacy']);
        Route::get('/community-impact/leaderboard', [CommunityImpactController::class, 'leaderboard']);
        Route::post('/reports', [CityServiceController::class, 'reportIssue']);
        Route::get('/reports', [CityServiceController::class, 'reports']);
        Route::get('/reports/{report}', [CityServiceController::class, 'showReport']);
        Route::patch('/reports/{report}/status', [CityServiceController::class, 'updateReportStatus']);
        Route::post('/reports/{report}/updates', [CityServiceController::class, 'addReportUpdate']);
        Route::get('/my-reports', [CityServiceController::class, 'myReports']);
        Route::post('/alerts', [CityServiceController::class, 'createAlert']);
        Route::post('/post-drafts/preview', [PostDraftController::class, 'preview']);
        Route::get('/saved-items', [SavedItemController::class, 'index']);
        Route::post('/saved-items', [SavedItemController::class, 'store']);
        Route::delete('/saved-items', [SavedItemController::class, 'destroy']);

        Route::post('/listings', [ListingController::class, 'store']);
        Route::put('/listings/{listing}', [ListingController::class, 'update']);
        Route::get('/my-listings', [ListingController::class, 'mine']);
        Route::post('/store/products', [ProductController::class, 'store']);
        Route::put('/store/products/{product}', [ProductController::class, 'update']);
        Route::get('/hire/bookings', [HireBookingController::class, 'index']);
        Route::get('/hire/bookings/{hireBooking}', [HireBookingController::class, 'show']);
        Route::post('/hire/items/{hireItem}/book', [HireItemController::class, 'book']);
        Route::post('/hire/bookings/{hireBooking}/cancel', [HireBookingController::class, 'cancel']);
        Route::post('/hire/bookings/{hireBooking}/rate', [HireBookingController::class, 'rate']);
        Route::get('/hire/my-items', [HireItemController::class, 'myItems']);
        Route::post('/hire/items', [HireItemController::class, 'store']);
        Route::patch('/hire/items/{hireItem}', [HireItemController::class, 'update']);
        Route::delete('/hire/items/{hireItem}', [HireItemController::class, 'destroy']);
        Route::get('/hire/owner/bookings', [HireBookingController::class, 'ownerBookings']);
        Route::post('/hire/bookings/{hireBooking}/accept', [HireBookingController::class, 'accept']);
        Route::post('/hire/bookings/{hireBooking}/reject', [HireBookingController::class, 'reject']);
        Route::post('/hire/bookings/{hireBooking}/confirm', [HireBookingController::class, 'confirm']);
        Route::post('/hire/bookings/{hireBooking}/handed-over', [HireBookingController::class, 'handedOver']);
        Route::post('/hire/bookings/{hireBooking}/returned', [HireBookingController::class, 'returned']);
        Route::post('/hire/bookings/{hireBooking}/complete', [HireBookingController::class, 'complete']);
        Route::post('/accommodations', [AccommodationController::class, 'store']);
        Route::put('/accommodations/{accommodation}', [AccommodationController::class, 'update']);
        Route::middleware('role:seller|service_provider|business_owner|organization_admin|municipality_admin|town_manager|super_admin')->group(function (): void {
            Route::get('/my-businesses', [BusinessController::class, 'index']);
            Route::post('/my-businesses', [BusinessController::class, 'store']);
            Route::put('/my-businesses/{organization}', [BusinessController::class, 'update']);
            Route::post('/my-businesses/{organization}/logo', [BusinessController::class, 'uploadLogo']);
            Route::get('/my-businesses/{organization}/followers', [BusinessController::class, 'followers']);
            Route::post('/my-businesses/{organization}/alerts', [BusinessController::class, 'alerts']);
        });

        Route::post('/jobs', [JobController::class, 'store']);
        Route::post('/jobs/{job}/apply', [JobController::class, 'apply']);
        Route::get('/my-jobs', [JobController::class, 'mine']);

        Route::post('/worker-profile', [WorkerController::class, 'store']);

        Route::get('/bookings', [BookingController::class, 'index']);
        Route::post('/bookings', [BookingController::class, 'store']);
        Route::put('/bookings/{booking}/status', [BookingController::class, 'updateStatus']);
        Route::get('/provider/bookings', [ServiceProviderController::class, 'providerBookings']);

        Route::post('/provider-profile', [ServiceProviderController::class, 'storeProvider']);
        Route::put('/provider-profile/{serviceProvider}', [ServiceProviderController::class, 'updateProvider']);
        Route::post('/services', [ServiceProviderController::class, 'storeService']);
        Route::post('/availability', [ServiceProviderController::class, 'storeAvailability']);

        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::get('/notifications/unread', [NotificationController::class, 'index']);
        Route::post('/notifications/{id}/read', [NotificationController::class, 'markRead']);
        Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead']);
        Route::post('/notifications/mark-read', [NotificationController::class, 'markAllRead']);
        Route::post('/device-tokens', [DeviceTokenController::class, 'store']);
        Route::delete('/device-tokens/{deviceToken}', [DeviceTokenController::class, 'destroy']);
        Route::get('/conversations', [ConversationController::class, 'index']);
        Route::get('/conversations/{conversation}', [ConversationController::class, 'show']);
        Route::post('/conversations', [ConversationController::class, 'store']);
        Route::post('/conversations/{conversation}/messages', [ConversationController::class, 'message']);
        Route::post('/messages/{message}/read', [ConversationController::class, 'markRead']);

        Route::get('/deliveries', [DeliveryController::class, 'index']);
        Route::post('/deliveries/estimate', [DeliveryController::class, 'estimate']);
        Route::post('/deliveries/request', [DeliveryController::class, 'store']);
        Route::get('/deliveries/current', [DeliveryController::class, 'current']);
        Route::post('/deliveries', [DeliveryController::class, 'store']);
        Route::get('/deliveries/{delivery}', [DeliveryController::class, 'show']);
        Route::patch('/deliveries/{delivery}/cancel', [DeliveryController::class, 'cancel']);
        Route::post('/deliveries/{delivery}/rate', [DeliveryController::class, 'rate']);
        Route::get('/rides', [RideController::class, 'index']);
        Route::post('/rides/estimate', [RideController::class, 'estimate']);
        Route::post('/rides/request', [RideController::class, 'store']);
        Route::get('/rides/current', [RideController::class, 'current']);
        Route::post('/rides', [RideController::class, 'store']);
        Route::get('/rides/{ride}', [RideController::class, 'show']);
        Route::patch('/rides/{ride}/cancel', [RideController::class, 'cancel']);
        Route::post('/rides/{ride}/rate', [RideController::class, 'rate']);
        Route::get('/orders', [OrderController::class, 'index']);
        Route::post('/orders', [OrderController::class, 'store']);
        Route::get('/orders/{order}', [OrderController::class, 'show']);
        Route::post('/orders/{order}/cancel', [OrderController::class, 'cancel']);
        Route::post('/orders/{order}/rate', [OrderController::class, 'rate']);
        Route::get('/sos', [SosController::class, 'index']);
        Route::post('/sos', [SosController::class, 'store']);
        Route::get('/my/events', [EventController::class, 'myEvents']);
        Route::get('/my/tickets', [EventController::class, 'myTickets']);
        Route::post('/events/{event}/save', [EventController::class, 'save']);
        Route::delete('/events/{event}/save', [EventController::class, 'unsave']);
        Route::post('/events/{event}/reminders', [EventController::class, 'reminder']);
        Route::post('/events/{event}/tickets/reserve', [EventController::class, 'reserveTicket']);
        Route::post('/events', [EventController::class, 'create']);
        Route::put('/events/{event}', [EventController::class, 'update']);
        Route::delete('/events/{event}', [EventController::class, 'destroy']);
        Route::post('/events/{event}/ticket-types', [EventController::class, 'addTicketType']);
        Route::put('/event-ticket-types/{ticketType}', [EventController::class, 'updateTicketType']);
        Route::get('/events/{event}/tickets', [EventController::class, 'eventTickets']);
        Route::post('/tickets/{ticket}/cancel', [EventController::class, 'cancelTicket']);
        Route::post('/tickets/{ticket}/check-in', [EventController::class, 'checkIn']);
        Route::post('/safety-reports', [SafetyController::class, 'store']);
        Route::post('/moderation-flags', [ModerationController::class, 'store']);
        Route::get('/blocks', [BlockController::class, 'index']);
        Route::post('/blocks', [BlockController::class, 'store']);
        Route::delete('/blocks/{block}', [BlockController::class, 'destroy']);

        Route::middleware('role:operator|municipality_admin|town_manager|super_admin')->group(function (): void {
            Route::get('/admin/summary', [AdminController::class, 'summary']);
            Route::get('/admin/overview', [AdminController::class, 'overview']);
            Route::get('/admin/municipality-dashboard', [AdminController::class, 'municipalityDashboard']);
            Route::get('/admin/system-health', [AdminController::class, 'systemHealth']);
            Route::get('/admin/audit-logs', [AdminController::class, 'auditLogs']);
            Route::get('/admin/feature-flags', [AdminController::class, 'featureFlags']);
            Route::get('/admin/towns', [AdminController::class, 'towns']);
            Route::get('/admin/users', [AdminController::class, 'users']);
            Route::get('/admin/orders', [AdminOrderController::class, 'index']);
            Route::get('/admin/orders/{order}', [AdminOrderController::class, 'show']);
            Route::get('/admin/hire/items', [AdminHireController::class, 'items']);
            Route::get('/admin/hire/bookings', [AdminHireController::class, 'bookings']);
            Route::post('/admin/hire/items/{hireItem}/approve', [AdminHireController::class, 'approve']);
            Route::post('/admin/hire/items/{hireItem}/reject', [AdminHireController::class, 'reject']);
            Route::post('/admin/hire/bookings/{hireBooking}/resolve-dispute', [AdminHireController::class, 'resolveDispute']);
            Route::get('/admin/reports', [CityServiceController::class, 'reports']);
            Route::get('/admin/news-sources', [NewsSourceController::class, 'index']);
            Route::post('/admin/news-sources', [NewsSourceController::class, 'store']);
            Route::put('/admin/news-sources/{newsSource}', [NewsSourceController::class, 'update']);
            Route::post('/admin/news-sources/{newsSource}/fetch', [NewsSourceController::class, 'fetch']);
            Route::put('/admin/news-items/{newsItem}', [NewsSourceController::class, 'updateItem']);
            Route::put('/admin/reports/{report}/status', [CityServiceController::class, 'updateReportStatus']);
            Route::post('/admin/announcements', [CityServiceController::class, 'createAnnouncement']);
            Route::get('/admin/community-projects', [AdminCommunityProjectController::class, 'index']);
            Route::get('/admin/community-projects/pending', [AdminCommunityProjectController::class, 'pending']);
            Route::get('/admin/community-projects/{id}', [AdminCommunityProjectController::class, 'show']);
            Route::patch('/admin/community-projects/{id}/approve', [AdminCommunityProjectController::class, 'approve']);
            Route::patch('/admin/community-projects/{id}/reject', [AdminCommunityProjectController::class, 'reject']);
            Route::patch('/admin/community-projects/{id}/request-changes', [AdminCommunityProjectController::class, 'requestChanges']);
            Route::patch('/admin/community-projects/{id}/feature', [AdminCommunityProjectController::class, 'feature']);
            Route::patch('/admin/community-projects/{id}/status', [AdminCommunityProjectController::class, 'status']);
            Route::delete('/admin/community-projects/{id}', [AdminCommunityProjectController::class, 'destroy']);
            Route::get('/admin/moderation-flags', [ModerationController::class, 'index']);
            Route::put('/admin/moderation-flags/{moderationFlag}', [ModerationController::class, 'update']);
            Route::get('/admin/safety-flags', [SafetyController::class, 'flags']);
            Route::put('/admin/suspend', [SafetyController::class, 'suspend']);
            Route::get('/admin/community-impact/pending', [AdminCommunityImpactController::class, 'pending']);
            Route::post('/admin/community-impact/award', [AdminCommunityImpactController::class, 'award']);
            Route::patch('/admin/community-impact/transactions/{id}/approve', [AdminCommunityImpactController::class, 'approveTransaction']);
            Route::patch('/admin/community-impact/transactions/{id}/reject', [AdminCommunityImpactController::class, 'rejectTransaction']);
            Route::patch('/admin/community-impact/transactions/{id}/reverse', [AdminCommunityImpactController::class, 'reverseTransaction']);
            Route::get('/admin/community-impact/users/{user_id}', [AdminCommunityImpactController::class, 'userProfile']);
            Route::get('/admin/community-impact/redemptions', [AdminCommunityImpactController::class, 'redemptions']);
            Route::patch('/admin/community-impact/redemptions/{id}/approve', [AdminCommunityImpactController::class, 'approveRedemption']);
            Route::patch('/admin/community-impact/redemptions/{id}/fulfill', [AdminCommunityImpactController::class, 'fulfillRedemption']);
            Route::patch('/admin/community-impact/redemptions/{id}/reject', [AdminCommunityImpactController::class, 'rejectRedemption']);
            Route::post('/admin/community-impact/rewards', [AdminCommunityImpactController::class, 'createReward']);
            Route::patch('/admin/community-impact/rewards/{id}', [AdminCommunityImpactController::class, 'updateReward']);
            Route::get('/admin/feed/pending', [AdminFeedController::class, 'pending']);
            Route::post('/admin/feed', [AdminFeedController::class, 'store']);
            Route::patch('/admin/feed/{feedPost}/approve', [AdminFeedController::class, 'approve']);
            Route::patch('/admin/feed/{feedPost}/reject', [AdminFeedController::class, 'reject']);
            Route::patch('/admin/feed/{feedPost}/feature', [AdminFeedController::class, 'feature']);
            Route::get('/admin/role-applications', [AdminRoleApplicationController::class, 'index']);
            Route::get('/admin/role-applications/{id}', [AdminRoleApplicationController::class, 'show']);
            Route::patch('/admin/role-applications/{id}/approve', [AdminRoleApplicationController::class, 'approve']);
            Route::patch('/admin/role-applications/{id}/reject', [AdminRoleApplicationController::class, 'reject']);
            Route::patch('/admin/role-applications/{id}/request-changes', [AdminRoleApplicationController::class, 'requestChanges']);
            Route::patch('/admin/users/{id}/roles/{role}/suspend', [AdminRoleApplicationController::class, 'suspendUserRole']);
        });

        Route::middleware('role:driver|super_admin')->group(function (): void {
            Route::patch('/driver/availability', [RideController::class, 'updateAvailability']);
            Route::get('/driver/ride-requests', [RideController::class, 'driverRequests']);
            Route::post('/driver/rides/{ride}/accept', [RideController::class, 'accept']);
            Route::post('/driver/rides/{ride}/decline', [RideController::class, 'decline']);
            Route::patch('/driver/rides/{ride}/arrived', [RideController::class, 'arrived']);
            Route::patch('/driver/rides/{ride}/start', [RideController::class, 'start']);
            Route::patch('/driver/rides/{ride}/complete', [RideController::class, 'complete']);
            Route::get('/driver/trips', [RideController::class, 'trips']);
            Route::get('/driver/earnings', [RideController::class, 'earnings']);
        });

        Route::middleware('role:courier|super_admin')->group(function (): void {
            Route::patch('/courier/availability', [DeliveryController::class, 'updateAvailability']);
            Route::get('/courier/delivery-requests', [DeliveryController::class, 'courierRequests']);
            Route::post('/courier/deliveries/{delivery}/accept', [DeliveryController::class, 'accept']);
            Route::post('/courier/deliveries/{delivery}/decline', [DeliveryController::class, 'decline']);
            Route::patch('/courier/deliveries/{delivery}/pickup-confirmed', [DeliveryController::class, 'pickupConfirmed']);
            Route::patch('/courier/deliveries/{delivery}/in-transit', [DeliveryController::class, 'inTransit']);
            Route::patch('/courier/deliveries/{delivery}/delivered', [DeliveryController::class, 'delivered']);
            Route::get('/courier/deliveries', [DeliveryController::class, 'deliveries']);
            Route::get('/courier/earnings', [DeliveryController::class, 'earnings']);
            Route::get('/courier/orders/available', [CourierOrderController::class, 'available']);
            Route::post('/courier/orders/{order}/accept', [CourierOrderController::class, 'accept']);
            Route::post('/courier/orders/{order}/picked-up', [CourierOrderController::class, 'pickedUp']);
            Route::post('/courier/orders/{order}/delivered', [CourierOrderController::class, 'delivered']);
        });

        Route::middleware('role:organization_admin|business_owner|super_admin')->group(function (): void {
            Route::post('/my-businesses/{organization}/news-sources', [NewsSourceController::class, 'storeForOrganization']);
        });

        Route::middleware('role:seller|business_owner|organization_admin|super_admin')->group(function (): void {
            Route::get('/seller/orders', [SellerOrderController::class, 'index']);
            Route::post('/seller/orders/{order}/accept', [SellerOrderController::class, 'accept']);
            Route::post('/seller/orders/{order}/reject', [SellerOrderController::class, 'reject']);
            Route::post('/seller/orders/{order}/preparing', [SellerOrderController::class, 'preparing']);
            Route::post('/seller/orders/{order}/ready', [SellerOrderController::class, 'ready']);
        });
    });
});
