import 'package:flutter/material.dart';

class AppColors {
  static const primaryGreen = Color(0xFF16A34A);
  static const primaryPurple = Color(0xFF3F2BCB);
  static const deepPurple = Color(0xFF2B1E8C);
  static const electricPurple = Color(0xFF5B44E0);
  static const accentGold = Color(0xFFFACC15);
  static const softBlue = Color(0xFF2563EB);
  static const deepCharcoal = Color(0xFF0F172A);
  static const softBackground = Color(0xFFF8FAFC);
  static const surfaceWhite = Color(0xFFFFFFFF);
  static const danger = Color(0xFFEF4444);
  static const success = Color(0xFF16A34A);
  static const warning = Color(0xFFF59E0B);
  static const info = softBlue;
  static const mutedText = Color(0xFF6B7280);
  static const border = Color(0xFFE5E7EB);
  static const darkBackground = softBackground;
  static const darkSurface = surfaceWhite;
  static const darkCard = surfaceWhite;
  static const darkTextPrimary = deepCharcoal;
  static const darkTextSecondary = mutedText;
  static const darkBorder = border;
  static const glassLight = surfaceWhite;
  static const glassDark = surfaceWhite;
  static const goldSoft = Color(0xFFFEF3C7);
  static const infoSoft = Color(0xFFE8F0FF);
  static const successSoft = Color(0xFFEAF8EF);
  static const warningSoft = Color(0xFFFFF4DD);
  static const purpleSoft = Color(0xFFEEEAFE);
  static const purpleSoftAlt = Color(0xFFF5F2FF);
  static const purpleBorder = Color(0xFFD9D4FB);
  static const neutralSoft = Color(0xFFF3F4F6);
  static const neutralSoftAlt = Color(0xFFF8FAFF);
  static const lokalsGreen = primaryGreen;
  static const greenSoft = successSoft;
  static const skySoft = infoSoft;
  static const dangerSoft = Color(0xFFFEE2E2);
}
